@extends('layouts.app')

@section('content')
    <section>
        <div class="contained">
            <h1>Cymatrax Terms of Service</h1>
            <h2>Description of the Service</h2>
            <p>Cymatrax (&quot;<strong>Cymatrax</strong>&quot;, &quot;<strong>we</strong>&quot;, &quot;<strong>us</strong>&quot;, &quot;<strong>our</strong>&quot;) is an audio post production service, owned and operated by Cymatrax, Inc.<br>
                As a registered user of our &quot;<strong>Service</strong>&quot;, you (&quot;<strong>you</strong>&quot;, &quot;<strong>your</strong>&quot;) can upload digital audio files and other data or information (together, &quot;<strong>Content</strong>&quot;) and encapsulate them in &quot;<strong>Productions</strong>&quot; on our &quot;<strong>Website</strong>&quot; Cymatrax.com. Cymatrax will not store this Content in strict accordance with our <a href="{{URL::to('/')}}/privacy/">Privacy Policy</a> for the purpose of creating from it, at your direction, one or more new media files, which are also considered part of your Content. In particular, registered users can use Cymatrax.com to process any audio that they upload to a Production, for the purpose of applying automatic audio processing algorithms such as white noise reduction, adaptive level adjustments, etc. Users can also export the new media files created by Cymatrax.com to third-party services.</p>
            <h2>Acceptance of Terms of Service</h2>
            <p>The following terms and conditions govern all your use of our Service, including, but not limited to, the Website (Cymatrax.com) and all other apps, tools, data, software, APIs, content, products, and services available at or through the Website or otherwise provided by Cymatrax, Inc. The Service is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies and procedures that may be published from time to time on this Website by Cymatrax.com (collectively, the &quot;<strong>Agreement</strong>&quot;).</p>
            <p>Please read this Agreement carefully before accessing the website or using the Service. By accessing the Website or using any part of the Service, you automatically agree to become bound by the terms and conditions of this Agreement. If you do not agree to all the terms and conditions of this Agreement, then you may not access the Website or use any part of the Service. If these terms and conditions are considered an offer by Cymatrax, acceptance is expressly limited to these terms.</p>
            <h2>Your Cymatrax Account</h2>
            <p>If you register an &quot;<strong>Account</strong>&quot; on our Website, you are responsible for maintaining the security of your Account, and you are fully responsible for all activities that occur under the Account and any other actions taken in connection with your use of our Service. You must immediately notify Cymatrax of any unauthorized uses of your Account or any other breaches of security. Cymatrax will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.<br>
                It is Cymatrax's policy that, if your account information or Content stored on our servers is requested for the purpose of a legal investigation, we will notify you of this request prior to disclosure, unless otherwise prohibited by applicable law.</p>
            <h2>Your Content</h2>
            <p><strong>Cymtrax is not a data storage or backup service. </strong>We do not backup your Content, and <strong>you are responsible for keeping backups of your own work.</strong><br>
                Your Productions and any associated audio or video files will be permanently deleted from our servers including all its metadata and possible data from external services after a certain number of days, which we will announce on your Account's  production list  (21 days for audio, 7 days for video and API productions). We will, however, keep billing metadata associated with your Productions in an internal database (how many hours of audio you processed).</p>
            <p>Also, we might store selected audio and/or video files (or excerpts thereof) from your Content in an internal storage space for the purpose of improving our audio processing algorithms. You will not have access to either this internal database or storage space, and we do not guarantee that we will keep your metadata or audio or video files for any specific period of time.</p>
            <p>When using our Service, <strong>you fully retain any rights that you have with regards to your Content, including copyright.</strong> The only rights with regards to your Content that you grant Cymatrax are for the following two purposes:</p>
            <ul>
                <li>To run your Productions, such that Cymatrax can create new media files from your Content according to your instructions.</li>
                <li>To improve our audio processing algorithms. For this purpose, you agree that your Content may be viewed and/or listened to by a Cymatrax employee or any person contracted by Cymatrax to work on our audio processing algorithms.</li>
            </ul>
            <p>We will not share your Content, or metadata associated with or generated from your Content, with third parties. We might occasionally share statistical data concerning the Productions of our users with third parties, but if we do so, the data will be presented in an aggregated form that is not ascribable to an individual user.</p>
            <h2>Payments</h2>
            <p>One-time payments are available on the website. <strong>Paid fees are never refundable.</strong><br>
                Services with subscription (recurring) will be individually calculated and contracted through our sales department to individual subscribers. All inquiries to a custom rate of subscription should contact <a href="mailto:sales@cymatrax.com">sales@cymatrax.com</a> for individual pricing rates. <strong>Subscription payments</strong> will be charged on the day you sign up for the service and will cover the use of that service Subscription payments can be canceled at any time with notification to our sales department. There are no refunds for cost to user at agreed rate due to higher volume use of the Cymatrax technology. Volume contracted rates are good for one year from the date of signing. Any change or renegotiation of any contract “in service” must be ratified by our sales department prior to new rates applied to service. Failure to volume use during contracted year may incur additional charges on your account. Again, if for any reason your upload volume has an unforeseeable delay issue, contact our sales department.  If you fail to make payment for your selected service on time, we reserve the right to suspend your account, or reduce your service rates to individual service upload rates.<br>
                <strong>We may change terms and features for any contract accounts</strong> at any time but will give you advance notice of these changes via a message to the email address associated with your account.<br>
            </p>
            <h2>Your Responsibilities</h2>
            <p>If you make (or allow any third party to make) any of your Content available by means of our Service, you are entirely responsible for the content of, and any harm that may result from that Content. Such is the case regardless of whether the Content in question constitutes an audio file, a video file, or any other kind of data. By making your Content available on our Website or any third-party site through our Service, you represent and warrant that:</p>
            <ul>
                <li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li>
                <li>if your employer has rights to intellectual property you create, you have either</li>
                <ul>
                    <li>received permission from your employer to make available the Content, or</li>
                    <li>secured from your employer a waiver as to all rights in or to the Content;</li>
                </ul>
                <li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li>
                <li>the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content.</li>
                <li>Without limiting any of those representations or warranties, Cymatrax has the right (though not the obligation) to, in Cymatrax's sole discretion to:</li>
                <ul>
                    <li>refuse or remove any Content that, in Cymatrax's reasonable opinion, violates any Cymatrax policy or is in any way harmful or objectionable, or</li>
                    <li>terminate or deny access to and use of the Website to any individual or entity for any reason, in Cymatrax's sole discretion.</li>
                </ul>
            </ul>
            <h2>Other Websites and Services</h2>
            <p>We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which Cymatrax links, and/or that link to Cymatrax. Cymatrax does not have any control over those non-Cymatrax websites and webpages and is not responsible for their contents or their use. By linking to a non-Cymatrax website or webpage, Cymatrax does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Cymatrax disclaims any responsibility for any harm resulting from your use of non-Cymatrax websites and webpages.<br>
                Cymatrax offers an API (contact sales@cymatrax.com), by means of which our Service can be integrated into third-party applications. We are not responsible for how third-party developers handle your Content and your Cymatrax user credentials. If you are a third-party developer making use of the Cymatrax API, you agree not to misuse the Cymatrax user credentials of your users. See the Cymatrax API Docs for further information.	  </p>
            <h2>Copyright Infringement</h2>
            <p>As Cymatrax asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by Cymatrax.com violates your copyright, you are encouraged to notify Cymatrax. Cymatrax will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. Cymatrax will terminate a user's access to and use of the Website if, under appropriate circumstances, the user is determined to be a repeat infringer of the copyrights or other intellectual property rights of Cymatrax or others.</p>
            <h2>Changes to Terms of Service</h2>
            <p>Cymatrax reserves the right, in its sole discretion, to modify or replace any part of this Agreement. If this happens, we will publish the new version on our website. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. Cymatrax may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement.</p>
            <h2>Termination</h2>
            <p>Cymatrax may terminate your access to all or any part of our Service, and/or permanently delete any Content and data associated with your Account, at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your Cymatrax.com Account (if you have one), you may simply discontinue using the Website. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>
            <h2>Disclaimer of Warranties</h2>
            <p>The Website is provided &quot;as is&quot;. Cymatrax and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Cymatrax nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. By using our Service, you agree and understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</p>
            <h2>Limitation of Liability</h2>
            <p>In no event will Cymatrax, or its suppliers or licensors, be liable with respect to any subject matter of this Agreement under any contract, negligence, strict liability or other legal or equitable theory for:</p>
            <ul>
                <li>any special, incidental, or consequential damages</li>
                <li>the cost of procurement for substitute products or services</li>
                <li>for interruption of use or loss or corruption of data</li>
                <li>detrimental health issues incurred by usage of the Cymatrax technology</li>
                <li>Cymatrax shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent such is prohibited by applicable law</li>
            </ul>
            <h2>General Representation and Warranty</h2>
            <p>You represent and warrant that:<br>
                •	your usage of the Website will be in strict accordance with this Agreement and with all applicable laws and regulations (including without limitation any local laws or; regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the country in which you reside), and<br>
                •	your usage of the Website will not infringe or misappropriate the intellectual property rights of any third party.<br>
                •	you are at least eighteen (18) years of age and have permission to access the Cymatrax services by means to activate and operate this website, including the uploading of all payment information.</p>
            <h2>Indemnification</h2>
            <p>You agree to indemnify and hold harmless Cymatrax, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys' fees, arising out of your usage of the Cymatrax Website, its patented software, including but not limited to your violation of this Agreement.</p>
            <h2>Miscellaneous</h2>
            <p>This Agreement constitutes the entire Agreement between Cymatrax and you concerning the subject matter hereof, and it may only be modified by a written amendment signed by an authorized executive of Cymatrax, or by the posting by Cymatrax of a revised version on its website. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the United States of America, and the proper venue for any disputes arising out of or relating to any of the same will be the courts located in Dallas, Texas, USA.</p>
            <p>The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys' fees.  If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties' original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof.  You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; Cymatrax may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors, transferees, and permitted assigns.</p>
            <h1>&nbsp;</h1>
        </div>
    </section>


@endsection
