<?php $__env->startSection('content'); ?>
    <section class="inverted">
        <div class="contained">
            <h1>Cymatrax Audio Conversion Services</h1>
            <p>Cymatrax technology is the future of the world. Digital audio listeners exceed over 4B listeners each day. When we first started our journey to build our software, it was at first a task to find a developer having the skills to write acoustic base code. “It is one in a  thousand develpoers that have the skill to wrote such code. Good luck.” We were up for the challenge, and after searching over 1200 resumes, we found one man that could see our vision and chose to work with us. This search and development of our prototype took us over a year and another three to get this technology patented.</p>
            <p>We collected data from Johns Hopkins, the Mayo Clinic, Harvard School of Medicine, MIT and the Oxford Neurological Institute, where they all have been documenting how specific frequencies will travel efficiently through the central nervous system and optimize the efficiency of the signal to the brain. We also found the opposite from the National Institute of Health’s 2015 clinical trial report “Differencial effects of white noise in cognitive and perceptual tasks” where all subconscious behavior is slowed down. All of these frequencies are found in 99.9% of all digital audio. Building our technology was “absolutely logical” to fill an unknown need. </p>
            <p>Today, our technology has not only been applied to digital music, but to podcasts, cororate training, books on audio, online education. Soon we will release our technology in streaming media so that listeners will be able to listen in real time, as a plug-in for Internet video channels, car radios, headphones, speakers and even for retail shoppers to use, giving them better decision making abilities. </p>
            <p>We also are putting together research in the medical field, where two highly acclaimed neurosurgeons believe and have asked to oversee our technology in clinical trials to be used in daily therapy for autism. “It is logical, once showing ANY positive results in autism to use this in many other neurological disorders, such as Alzheimer’s, Parkenson’s, ADHD, PTSD, stroke and demensia.”</p>
            <p>With the new observational science of epigenetics, describing that each cell in the body is influenced by four enviraonmental influences, chemical, heat, light and sound, we vision the use of frequency/sound therapy to be used in the field of DNA therapy and modification. </p>
            <p>First and foremost, it is our mission to bring this technology to optimize the human potential. We are dedicated to use our revenue share in the digital audio market to continue research and give you a better life.</p>
        </div>
    </section>

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /opt/lampp/htdocs/cymatrax_waves/resources/views/services.blade.php ENDPATH**/ ?>